apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: depot-store
  namespace: vcf-depot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: token-store
  namespace: vcf-depot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-store
  namespace: vcf-depot
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi