apiVersion: v1
kind: Secret
metadata:
  name: vcf-depot-secrets
  namespace: vcf-depot
type: Opaque
stringData:
  FLASK_SECRET_KEY: REPLACE_WITH_RANDOM_STRING
  ADMIN_USERNAME: admin
  ADMIN_PASSWORD: REPLACE_WITH_STRONG_PASSWORD