apiVersion: v1
kind: Service
metadata:
  name: vcf-depot-manager
  namespace: vcf-depot
  labels:
    app.kubernetes.io/name: vcf-depot-manager
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vcf-depot-manager
  ports:
    - name: http
      port: 5000
      targetPort: http
      protocol: TCP